version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/node:20.11.1
    steps:
      - checkout
      - run:
          name: Install dependencies with pnpm
          command: pnpm install
      - run:
          name: Building SDK
          command: pnpm run build
      - run:
          name: Run Biome linting
          command: pnpm run lint

  test:
    docker:
      - image: cimg/node:20.11.1
    steps:
      - checkout
      - run:
          name: Install dependencies with pnpm
          command: pnpm install
      - run:
          name: Run Vitest tests
          command: pnpm test

  release:
    docker:
      - image: cimg/node:20.11.1
    steps:
      - checkout
      - run:
          name: Install dependencies with pnpm
          command: pnpm install
      - run:
          name: Building SDK
          command: pnpm run build
      - run:
          name: Creating and publishing release
          command: pnpm run semantic-release

workflows:
  lint_and_test:
    jobs:
      - lint
      - test
      - release:
          requires:
            - lint
            - test
